export const AUTH_USER_NOT_EXIST_CODE     = 'AUTH_USER_NOT_EXIST_CODE';
export const AUTH_USER_ALREADY_EXIST_CODE = 'AUTH_USER_ALREADY_EXIST_CODE';
export const AUTH_NON_VALID_PASSWORD_CODE = 'AUTH_NON_VALID_PASSWORD_CODE';
export const AUTH_NON_VALID_DATA_CODE     = 'AUTH_NON_VALID_DATA_CODE';